# Generated by Django 4.1.1 on 2022-09-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_studentresult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentresult',
            table='student_result',
        ),
    ]
